### ISSUE TITLE
Where the image and captions come from?

### ISSUE THREAD

**Issue by linjing7** [StevenGrove/GPT4Tools#25]
Hi, thanks for your great work! I have a question about the data generation:
Could you please tell me which datasets the images and captions come from?

**Comment by Yangr116** [comment]
We based on COCO dataset

**Comment by linjing7** [comment]
Okay, thanks for your kind reply!

**Comment by linjing7** [comment]
Hi, there are five captions for each image in COCO, do you use all the captions or randomly choose one?

**Comment by Yangr116** [comment]
We use 5 captions, or you can use the llava-instruction dataset, which
generates dense captions.


linjing7 ***@***.***> 于2023年12月19日周二 22:44写道：

**Comment by linjing7** [comment]
Okay, thanks for your reply.
