### ISSUE TITLE
Context Sample Generation

### ISSUE THREAD

**Issue by linjing7** [StevenGrove/GPT4Tools#26]
Hi, thanks for your excellent work! 

I notice that your dataset also includes some context samples. I'm wondering if these context samples are generated by GPT3.5? Or generated by manually designed rules?

**Comment by Yangr116** [comment]
according to manually designed rules.

linjing7 ***@***.***>于2023年12月22日 周五22:11写道：

**Comment by linjing7** [comment]
Thanks for your quick response! Is it achieved by a function in [generate_annotation.py](https://github.com/AILab-CVC/GPT4Tools/blob/master/gpt4tools/data/generate_annoations.py)? By the way, I notice that in multi-turn conversation, sometimes we do not hope to update the `input image path` with the `output image path` in last turn. Do we need to regenerate the context samples to achieve this target?

**Comment by linjing7** [comment]
Sorry for the confusion. Here the context sample refers to the case that uses multiple tools.

**Comment by linjing7** [comment]
BTW, I'm wondering if it is possible to add your WeChat? I'm also a student from SIGS. My WeChat is 15625292431.

**Comment by Yangr116** [comment]
I think image path in the dataset is taken as a pseudo argument. If you
want to achieve your objective in a demo, you can fix the image path. At
the same time, you can also try your idea to achieve it.

linjing7 ***@***.***>于2023年12月22日 周五22:18写道：

**Comment by Yangr116** [comment]
OK

linjing7 ***@***.***>于2023年12月22日 周五22:25写道：

**Comment by linjing7** [comment]
Okay, thanks for your kind reply!
